name: Keep Streamlit App Awake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  ping-app:
    runs-on: ubuntu-latest

    steps:
      - name: Send Ping Request
        run: |
          curl --max-time 30 -s -o /dev/null -w "%{http_code}\n" "https://phishguard-m9a7niypmmgckhhrkxrone.streamlit.app/"
